<div class="footer">
<table>
<tr>
<td class="footer-left">
<a href="http://theonlinemcmc.com">The Online MCMC</a><br>
&copy; Matthew Pitkin (2015)
</td>
<td class="footer-right">
The code for this site is licensed under the <a href="http://opensource.org/licenses/MIT">MIT license</a>.
It is available on <a href="https://github.com/mattpitkin/theonlinemcmc">github</a> and <a href="https://bitbucket.org/mattpitkin/theonlinemcmc">bitbucket</a>.
</td>
</tr>
</table>
</div>
