<div class="footer">
<table>
<tr>
<td class="footer-left">
<a href="http://www.theonlinemcmc.com">The Online MCMC</a><br>
&copy; Matthew Pitkin (2015)
</td>
<td class="footer-right">
The code for this site is licensed under the <a href="http://opensource.org/licenses/MIT">MIT license</a>.
It is available on <a href="https://github.com/mattpitkin/theonlinemcmc">github</a> and <a href="https://bitbucket.org/mattpitkin/theonlinemcmc">bitbucket</a>.
</td>
</tr>
</table>
</div>

<div class="acknowledgment">
This site is kindly hosted by the <a href="http://www.gla.ac.uk/schools/physics/">School of Physics & Astronomy</a> at the <a href="http://www.gla.ac.uk/">University of Glasgow</a>. They bear no reponsibility for the content of this site or the results that are produced.
</div>
